### ISSUE TITLE
FatalThrowableError

### ISSUE THREAD

**Issue by davehodg** [opendataedu/open-data-education-datasets#1]
curl -X GET --header 'Accept: application/xml' 'https://api.opendata.education/rest/sif/requests/SchoolInfos?Town=Cardiff&navigationPage=21&navigationPageSize=1000'

Gave me:

<img width="1021" alt="screen shot 2018-04-09 at 18 37 18" src="https://user-images.githubusercontent.com/922517/38513091-14d7fe92-3c25-11e8-9818-ae76e834891c.png">

Ideas?

**Comment by davehodg** [comment]
https://api.opendata.education/rest/sif/requests/SchoolInfos?navigationPage=1&navigationPageSize=100

Just did too.

**Comment by davehodg** [comment]
Now it's working. Must have been a bogon.

**Comment by drjonnicholson** [comment]
Thanks for the heads-up, We'd been swamped in other work but I've just managed for find a day to do some updates etc. Updated a lot of dependencies, debugged the error you saw, and the platform should be more stable now.

I'll close for now, but keep us posted if you have any further issues - can always reopen.

**Comment by davehodg** [comment]
Aside from the IP internal server erroring after 20x100 schools...

Useful resource though!
